### ISSUE TITLE
Can't compile master branch

### ISSUE THREAD

**Issue by ghost** [aither64/haveclip-desktop#1]
I'm getting that error when i try to compile master branch.
![screenshot_20170205_172037](https://cloud.githubusercontent.com/assets/14142472/22627683/bd8bb7cc-ebc7-11e6-8e3c-c4c1dc115a24.png)

**Comment by aither64** [comment]
I've always compiled HaveClip for desktop with Qt4, but it appears this was the only compatibility issue preventing successful build with Qt5. It should be fixed by commit fa5b6e857f37c71f7fa81cd3ebf541087533ee3d. So please pull the new commit and try to build it again.
